server:
  port: 8087

spring:
  kafka:
    consumer:
      group-id: test-consumer
      #是否开启自动提交
      enable-auto-commit: true
      #自动提交的时间间隔
      auto-commit-interval: 1000ms
      #key的解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value的解码方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #Kafka中没有初始偏移或如果当前偏移在服务器上不再存在时,默认区最新 ，有三个选项 【latest, earliest, none】
      auto-offset-reset: latest
      bootstrap-servers: 172.18.20.46:9092,172.18.20.46:9093,172.18.20.46:9094
      properties:
        session.timeout.ms: 60000
      heartbeat-interval: 30000

kafka:
  custom:
    topic: topic-ideal